### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by ChenOuyang** [computationalmodelling/fidimag#150]
In the fidimag folder, the MAKE procedure failed, and the issues in the terminal are listed below:
the repeated  error loops occurred during the procesure

(base) Chens-MacBook-Pro:~ chenouyang$ cd /Users
(base) Chens-MacBook-Pro:Users chenouyang$ cd fidimag-3.0/
(base) Chens-MacBook-Pro:fidimag-3.0 chenouyang$ make
python3 setup.py build_ext --inplace -j2
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Using CC=gcc-5
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Found User Module: example
Building with 8 threads
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Using CC=gcc-5
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Found User Module: example
Building with 8 threads
Using CC=gcc-5
Found User Module: example
Building with 8 threads
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fidimag-3.0/setup.py", line 274, in <module>
    ext_modules=cythonize(ext_modules, nthreads=nthreads),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
    pool = multiprocessing.Pool(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
Traceback (most recent call last):
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    exec(code, run_globals)
  File "/Users/fidimag-3.0/setup.py", line 274, in <module>
    ext_modules=cythonize(ext_modules, nthreads=nthreads),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    pool = multiprocessing.Pool(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    exec(code, run_globals)
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
  File "/Users/fidimag-3.0/setup.py", line 274, in <module>
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
    ext_modules=cythonize(ext_modules, nthreads=nthreads),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
Compiling /Users/fidimag-3.0/fidimag/atomistic/lib/clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/lib/common_clib.pyx because it changed.
    pool = multiprocessing.Pool(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
Compiling /Users/fidimag-3.0/fidimag/common/sundials/cvode.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/baryakhtar/baryakhtar_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/micro/lib/micro_clib.pyx because it changed.
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
Compiling /Users/fidimag-3.0/fidimag/common/neb_method/nebm_clib.pyx because it changed.
Compiling /Users/fidimag-3.0/fidimag/common/dipolar/dipolar.pyx because it changed.
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
Compiling /Users/fidimag-3.0/fidimag/atomistic/fmmlib/fmm.pyx because it changed.
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
Compiling /Users/fidimag-3.0/fidimag/user/example/example.pyx because it changed.
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main

**Comment by rpep** [comment]
Hi @ChenOuyang 

What version of MacOS are you using? I've never seen this issue before.

Best wishes,
Ryan

**Comment by ChenOuyang** [comment]
> Hi @ChenOuyang
> 
> What version of MacOS are you using? I've never seen this issue before.
> 
> Best wishes,
> Ryan

Hi @rpep 
It's macOS Big Sur 11.2.3, and I never compile any files before. Is it possible my Mac lacks of some compiler like Xcode?

Many thanks
Chen

**Comment by rpep** [comment]
Hi Chen,

Are you using one of the new ARM Macs? 

It looks like it could be a few things, but I'm not 100%. You're using a fairly old version of GCC. I have no idea if that will work on Big Sur, but might be worth upgrading. I use GCC 10 on my Mac which I install through Homebrew and that seems to work OK. Similarly, I'd install Python 3.8 through Homebrew; it looks like you might have installed a version through Python.org.

The actual error itself looks like it's failing to build in parallel, but this is odd - I've never seen this fail before. You can try modifying setup.py and changing nthreads to 1 so that it doesn't try and build in parallel perhaps?

Apologies I can't be any more help here,

Ryan

**Comment by rpep** [comment]
Close as
